### Site Settings ###
title: sseul's blog
description: >
  ì¸ê³µì§€ëŠ¥ì´ ì¢‹ì€ ì˜ˆìˆ˜ë¦¬ì˜ ë¸”ë¡œê·¸ ğŸš€
baseurl: "" # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository: seul1230/seul1230.github.io # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme: YoussefRaafatNasry/portfolYOU
open_new_tab: false # Opens external URLs in new tab (works for posts, projects and navbar only)
url: https://seul1230.github.io/

### Plugins ###
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-last-modified-at

### LastModifedAt Setting : Optional. The default date format, used if none is specified in the tag.
last-modified-at:
  date-format: "%d %b %Y"

### Navbar Settings ###
nav_exclude: # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/** # For Documentation Only

### Author Info ###
author:
  name: seul1230
  image: assets/icons/main.png
  # behance           : your_username
  # dribbble          : your_username
  email: pink0569@naver.com
  #  facebook          : your_username
  github: seul1230
  # gitlab            : your_username
  # instagram:
# kaggle            : your_username
# linkedin          : your_username
#medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements: # For Documentation Only
    output: true # For Documentation Only

### Disqus ###
disqus:
  shortname: # Your website Shortname on disqus

### Analytics ###
analytics:
  enabled: true # Set true to enable analytics
  google:
    tracking_id: G-Q6RR9JVN3Z

### Defaults for collections ###
defaults:
  - scope:
      path: "projects"
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: "blog"
      type: "posts"
    values:
      comments: true # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"

github: [metadata]
